#!/usr/bin/env bash
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
# shellcheck source=lib-release-assets.sh
# Resolved from this script's absolute repository root.
# shellcheck disable=SC1091
source "$root/scripts/lib-release-assets.sh"
# shellcheck source=lib-sha256.sh
# shellcheck disable=SC1091
source "$root/scripts/lib-sha256.sh"
directory=${1:-"$root/dist"}
version=${2:-0.1.0}
release_version_is_valid "$version" || {
  echo 'error: unsupported release version' >&2
  exit 1
}
[[ -d "$directory" ]] || { echo "error: missing asset directory $directory" >&2; exit 1; }
directory=$(cd "$directory" && pwd -P)
archive=$(release_source_archive "$version")
sbom=$(release_sbom "$version")
top="dekopon-python-provider-$version"

expected=$(release_asset_names "$version" | LC_ALL=C sort)
actual=$(find "$directory" -mindepth 1 -maxdepth 1 -type f -exec basename {} \; | LC_ALL=C sort)
[[ "$actual" == "$expected" ]] || {
  echo 'error: release asset layout differs from the immutable expected set' >&2
  diff -u <(printf '%s\n' "$expected") <(printf '%s\n' "$actual") >&2 || true
  exit 1
}

expected_checksum_names=$(release_asset_names "$version" | grep -Fvx SHA256SUMS)
actual_checksum_names=$(awk 'length($1) == 64 && $2 != "" {print $2}' "$directory/SHA256SUMS")
[[ "$actual_checksum_names" == "$expected_checksum_names" ]] || {
  echo 'error: SHA256SUMS does not cover the exact ordered asset set' >&2
  exit 1
}
(
  cd "$directory"
  sha256sum_check python-provider.wasm.sha256
  sha256sum_check "$archive.sha256"
  sha256sum_check SHA256SUMS
)

if command -v wasm-tools >/dev/null 2>&1; then
  wasm-tools validate "$directory/python-provider.wasm"
  "$root/scripts/assert-zero-core-imports.sh" "$directory/python-provider.wasm"
fi

python3 - "$directory/$archive" "$top" <<'PY'
import pathlib, sys, tarfile
archive, top = pathlib.Path(sys.argv[1]), sys.argv[2]
with archive.open("rb") as source:
    header = source.read(10)
if len(header) != 10 or header[:3] != b"\x1f\x8b\x08" or header[4:8] != b"\0\0\0\0":
    raise SystemExit("error: source archive is not deterministic gzip with mtime zero")
with tarfile.open(archive, "r:gz") as bundle:
    names = [member.name for member in bundle.getmembers()]
    if len(names) != len(set(names)):
        raise SystemExit("error: duplicate source archive member")
    for member in bundle.getmembers():
        path = pathlib.PurePosixPath(member.name)
        if path.is_absolute() or ".." in path.parts or path.parts[0] != top:
            raise SystemExit(f"error: unsafe source archive member {member.name}")
        if member.issym() or member.islnk() or member.isdev() or member.isfifo():
            raise SystemExit(f"error: unsupported source archive member {member.name}")
    required = {
        f"{top}/Cargo.lock",
        f"{top}/Cargo.toml",
        f"{top}/rust-toolchain.toml",
        f"{top}/wit/provider.wit",
        f"{top}/RELINKING.md",
        f"{top}/SOURCE_MANIFEST.json",
        f"{top}/SOURCE_FILE_SHA256SUMS",
        f"{top}/vendor/malachite-base-0.9.2/.cargo-checksum.json",
        f"{top}/vendor/malachite-bigint-0.9.2/.cargo-checksum.json",
        f"{top}/vendor/malachite-nz-0.9.2/.cargo-checksum.json",
        f"{top}/vendor/malachite-q-0.9.2/.cargo-checksum.json",
    }
    missing = sorted(required - set(names))
    if missing:
        raise SystemExit(f"error: source archive omits required members: {missing}")
PY

tar -xOf "$directory/$archive" "$top/$sbom" | cmp - "$directory/$sbom"
python3 - "$directory/$sbom" <<'PY'
import json, pathlib, sys
bom = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
if bom.get("bomFormat") != "CycloneDX" or bom.get("specVersion") != "1.5":
    raise SystemExit("error: expected CycloneDX 1.5 JSON SBOM")
metadata = bom.get("metadata", {})
if metadata.get("timestamp") != "1970-01-01T00:00:00.000000000Z":
    raise SystemExit("error: SBOM is not SOURCE_DATE_EPOCH reproducible")
tools = metadata.get("tools", [])
if not any(tool.get("name") == "cargo-cyclonedx" and tool.get("version") == "0.5.9" for tool in tools):
    raise SystemExit("error: SBOM was not generated by cargo-cyclonedx 0.5.9")
components = {(item.get("name"), item.get("version")) for item in bom.get("components", [])}
required = {(name, "0.9.2") for name in ("malachite-base", "malachite-bigint", "malachite-nz", "malachite-q")}
if not required <= components:
    raise SystemExit(f"error: SBOM omits exact Malachite components: {sorted(required - components)}")
PY

echo '20e50fe7aae3e56378ebf0417d9de904f55a0e61e4df315333e632a4d3555d95  LICENSE-LGPL-2.1' |
  (cd "$directory" && sha256sum_check -)
echo 'e3a994d82e644b03a792a930f574002658412f62407f5fee083f2555c5f23118  LICENSE-LGPL-3.0' |
  (cd "$directory" && sha256sum_check -)
echo '3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66d6af86c9dfb36986  LICENSE-GPL-3.0' |
  (cd "$directory" && sha256sum_check -)
for notice in \
  'malachite-base 0.9.2' \
  'malachite-bigint 0.9.2' \
  'malachite-nz 0.9.2' \
  'malachite-q 0.9.2' \
  'LGPL-3.0-only'; do
  grep -Fiq "$notice" "$directory/THIRD_PARTY_NOTICES.md" || {
    echo "error: release notice lacks $notice" >&2
    exit 1
  }
done
grep -Eiq 'corresponding[- ]source' "$directory/THIRD_PARTY_NOTICES.md" || {
  echo 'error: release notice lacks corresponding source' >&2
  exit 1
}
printf 'verified %s release assets for v%s\n' \
  "$(release_asset_names "$version" | wc -l | tr -d ' ')" "$version"
